#!/bin/bash

package_fullname=xlib_libXrender
package=libXrender
version=0.9.10
package_source=$package-$version.tar.bz2
package_url=http://xorg.freedesktop.org/releases/individual/lib/$package_source
