#!/bin/bash

run_command "cp $build_directory/cmake_build/bin/WPE{Database,Network,Web}Process \
  $target_directory/usr/bin/"
run_command "cp -d $build_directory/cmake_build/lib/libWPE* \
  $target_directory/usr/lib/"
run_command "DESTDIR=$target_directory \
  /usr/bin/cmake \
    -DCOMPONENT=Development \
    -P $build_directory/cmake_build/Source/JavaScriptCore/cmake_install.cmake"
run_command "DESTDIR=$target_directory \
  /usr/bin/cmake \
    -DCOMPONENT=Development \
    -P $build_directory/cmake_build/Source/WebKit2/cmake_install.cmake"

echo_color yellow "Fixing libtool files $package_fullname-$version"

echo_color yellow "Fixing pkg-config files $package_fullname-$version"

