#!/bin/bash

package_fullname=wpewebkit
package=wpewebkit
version=eafdc7f08cfc5a4a256dcff0c1881784fa4341fe
package_source=$package-$version.tar.gz
package_url=https://github.com/WebPlatformForEmbedded/WPEWebKit/archive/$version/$package_source
