#!/bin/bash

package_fullname=wpewebkit
package=wpewebkit
version=e19c99098fb2c1cfdc4c0ab46585e00580849519
package_source=$package-$version.tar.gz
package_url=https://github.com/WebPlatformForEmbedded/WPEWebKit/archive/$version/$package_source
