#!/bin/bash

package_fullname=wpewebkit
package=wpewebkit
version=5811a55428f6fa7631461002c65ed48ef86f44f8
package_source=$package-$version.tar.gz
package_url=https://github.com/WebPlatformForEmbedded/WPEWebKit/archive/$version/$package_source
