#!/bin/bash

package_fullname=libmng
package=libmng
version=2.0.3
package_source=$package-$version.tar.xz
package_url=http://downloads.sourceforge.net/project/$package/$package-devel/$version/$package_source
