#!/bin/bash

PATH="$_PATH" /usr/bin/make -j5 \
  DESTDIR=$target_directory installlib \
  -C $build_directory

echo_color yellow "Fixing libtool files $package-$version"

source $root_directory/tools/install-functions

update_references $target_directory/usr/lib* "*.la" $target_directory

echo_color yellow "Fixing pkg-config files $package-$version"

for directory in $target_directory/usr/lib/pkgconfig $target_directory/usr/share/pkgconfig; do
  if [ -d $directory ]; then
    update_references $directory "*.pc" $target_directory
  fi
done
