#!/bin/bash

echo $_PATH_LOCAL

PATH="$_PATH_LOCAL" \
PKG_CONFIG="$_PKG_CONFIG" \
PKG_CONFIG_SYSROOT_DIR="/" \
PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 \
PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 \
PKG_CONFIG_LIBDIR="$staging_directory/usr/lib/pkgconfig:$staging_directory/usr/share/pkgconfig"
AR="$_AR" AS="$_AS" LD="$_LD" NM="$_NM" \
CC="$_CC" GCC="$_GCC" CPP="$_CPP" CXX="$_CXX" \
FC="$_FC" F77="$_F77" \
RANLIB="$_RANLIB" \
OBJCOPY="$_OBJCOPY" \
CPPFLAGS="-I$staging_directory/usr/include" \
CFLAGS="-O2 -I$staging_directory/usr/include" \
CXXFLAGS="-O2 -I$staging_directory/usr/include" \
LDFLAGS="-L$staging_directory/lib -L$staging_directory/usr/lib -Wl,-rpath,$staging_directory/usr/lib" \
INTLTOOL_PERL=/usr/bin/perl \
AUTOM4TE=/usr/bin/autom4te \
gettext_datadir=$staging_directory/usr/share/gettext \
$staging_directory/usr/bin/gettextize -f