#!/bin/bash

package_fullname=gst1-plugins-base
package=gst-plugins-base
version=1.10.4
package_source=$package-$version.tar.xz
package_url=https://gstreamer.freedesktop.org/src/$package/$package_source
