#!/bin/bash

package_fullname=xproto_renderproto
package=renderproto
version=0.11.1
package_source=$package-$version.tar.bz2
package_url=http://xorg.freedesktop.org/releases/individual/proto/$package_source
