#!/bin/bash

package_fullname=wpelauncher
package=wpelauncher
version=bee8c4dfbb437e1865b93f96898078b9279220ef
package_source=$package-$version.tar.gz
package_url=https://github.com/WebPlatformForEmbedded/WPEWebKitLauncher/archive/$version/$package_source
