#!/bin/bash

package_fullname=glib-networking
package=glib-networking
version=2.50.0
package_source=$package-$version.tar.xz
package_url=http://ftp.gnome.org/pub/gnome/sources/$package/2.50/$package_source
