#!/bin/bash

package_fullname=xproto_inputproto
package=inputproto
version=2.3.2
package_source=$package-$version.tar.bz2
package_url=http://xorg.freedesktop.org/releases/individual/proto/$package_source
