#!/bin/bash

package_fullname=xproto_xextproto
package=xextproto
version=7.3.0
package_source=$package-$version.tar.bz2
package_url=http://xorg.freedesktop.org/releases/individual/proto/$package_source
