#!/bin/bash

PATH="$_PATH" /usr/bin/make -j5 \
  -C $build_directory \
  INSTALL_PREFIX=$target_directory

echo_color yellow "Fixing libtool files $package_fullname-$version"

for directory in $target_directory/usr/lib*; do
  if [ -d $directory ]; then
    update_references $directory "*.la" $target_directory
    if [ $? -ne 0 ]; then
      exit 1
    fi
  fi
done

echo_color yellow "Fixing pkg-config files $package_fullname-$version"

for directory in $target_directory/usr/lib/pkgconfig $target_directory/usr/share/pkgconfig; do
  if [ -d $directory ]; then
    update_references $directory "*.pc" $target_directory
    if [ $? -ne 0 ]; then
      exit 1
    fi
  fi
done
