#!/bin/bash

package_fullname=xproto_xf86bigfontproto
package=xf86bigfontproto
version=1.2.0
package_source=$package-$version.tar.bz2
package_url=http://xorg.freedesktop.org/releases/individual/proto/$package_source
