#!/bin/bash

PATH="$_PATH" /usr/bin/make -j5 \
  DESTDIR=$staging_directory install \
  -C $build_directory

echo_color yellow "Fixing package configuration $package_fullname-$version"

/bin/sed -i -e "s,$output_directory,@BASE_DIR@,g" \
  -e "s,$staging_directory,@STAGING_DIR@,g" \
  -e "s,^\(exec_\)\?prefix=.*,\1prefix=@STAGING_DIR@/usr,g" \
  -e "s|\([\"'= ]\)/usr|\\1@STAGING_DIR@/usr|g" \
  -e "s|-I/usr/|-I@STAGING_DIR@/usr/|g" \
  -e "s|-L/usr/|-L@STAGING_DIR@/usr/|g" \
  -e "s,@STAGING_DIR@,$staging_directory,g" \
  -e "s,@BASE_DIR@,$output_directory,g" \
  $staging_directory/usr/bin/gpg-error-config ;

echo_color yellow "Fixing libtool files $package_fullname-$version"

for directory in $staging_directory/usr/lib*; do
  if [ -d $directory ]; then
    update_references $directory "*.la" $staging_directory
    if [ $? -ne 0 ]; then
      exit 1
    fi
  fi
done

echo_color yellow "Fixing pkg-config files $package_fullname-$version"

for directory in $staging_directory/usr/lib/pkgconfig $staging_directory/usr/share/pkgconfig; do
  if [ -d $directory ]; then
    update_references $directory "*.pc" $staging_directory
    if [ $? -ne 0 ]; then
      exit 1
    fi
  fi
done
