#!/bin/bash

package_fullname=xlib_libXdamage
package=libXdamage
version=1.1.4
package_source=$package-$version.tar.bz2
package_url=http://xorg.freedesktop.org/releases/individual/lib/$package_source
