#!/bin/bash

package_fullname=xproto_dri2proto
package=dri2proto
version=2.8
package_source=$package-$version.tar.bz2
package_url=http://xorg.freedesktop.org/releases/individual/proto/$package_source
