#!/bin/bash

package_fullname=xproto_fixesproto
package=fixesproto
version=5.0
package_source=$package-$version.tar.bz2
package_url=http://xorg.freedesktop.org/releases/individual/proto/$package_source
