#!/bin/bash

host_directory=$output_directory/host

PATH="$_PATH" \
PKG_CONFIG="/usr/bin/pkg-config" \
PKG_CONFIG_SYSROOT_DIR="/" \
PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 \
PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 \
PKG_CONFIG_LIBDIR="/usr/lib/pkgconfig:/usr/share/pkgconfig" \
CPATH=$host_directory/usr/include \
/usr/bin/make -j5 -C $build_directory/source
