#!/bin/bash

package_name=$1

root_directory=$(pwd)
script_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $root_directory

source $script_directory/functions

. $root_directory/package/$package_name/package

. $root_directory/tools/setenv

echo_color yellow "Building $package_fullname-$version"

run_command "cd $build_directory"

. $root_directory/package/$package_name/build
if [ $? -ne 0 ]; then
  echo_color red "Building $package_fullname-$version failed!"
  exit 1
fi

run_command "touch $build_directory/.stamp_built"
