#!/bin/bash

package_name=$1

root_directory=$(pwd)
script_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $root_directory

source $script_directory/functions

. $root_directory/package/$package_name/package

. $root_directory/tools/setenv

echo_color green "Cleaning $package_fullname-$version"

rm -rf $build_directory
if [ $? -ne 0 ]; then
  echo_color red "Cleaning $package_fullname-$version failed!"
  exit 1
fi

exit 0