#!/bin/bash

function make_color {
	color=$1
	case $color in
		black)
			printf '\033[0;30m'
			;;
		red)
			printf '\033[0;31m'
			;;
		green)
			printf '\033[0;32m'
			;;
		orange)
			printf '\033[0;33m'
			;;
		blue)
			printf '\033[0;34m'
			;;
		purple)
			printf '\033[0;35m'
			;;
		cyan)
			printf '\033[0;36m'
			;;
		lightgray)
			printf '\033[0;37m'
			;;
		darkgray)
			printf '\033[1;30m'
			;;
		lightred)
			printf '\033[1;31m'
			;;
		lightgreen)
			printf '\033[1;32m'
			;;
		yellow)
			printf '\033[1;33m'
			;;
		lightblue)
			printf '\033[1;34m'
			;;
		lightpurple)
			printf '\033[1;35m'
			;;
		lightcyan)
			printf '\033[1;36m'
			;;
		white)
			printf '\033[1;37m'
			;;
		default)
			printf '\033[0m'
			;;
	esac
}

function echo_color {
	color=$1
	shift 1
	make_color $color
	echo $@
	make_color default
}

function run_command {
    echo_color white $@
    eval $@
    local status=$?
    if [ $status -ne 0 ]; then
        echo_color red "Error running command" >&2
    fi
    return $status
}
