#!/bin/bash

package_name=$1

root_directory=$(pwd)
script_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $root_directory

source $script_directory/functions
source $root_directory/tools/install-functions

. $root_directory/package/$package_name/package

. $root_directory/tools/setenv

echo_color yellow "Installing $package_fullname-$version to target"

run_command "cd $build_directory"

if [ -f $root_directory/package/$package_name/install ]; then
	. $root_directory/package/$package_name/install
else
	install_files install $target_directory
fi
if [ $? -ne 0 ]; then
  echo_color red "Installing $package_fullname-$version to target failed!"
  exit 1
fi

if [ -f $root_directory/package/$package_name/post-install ]; then
  echo_color green "Running post-patch"
  . $root_directory/package/$package_name/post-install
fi

run_command "touch $build_directory/.stamp_target_installed"
