#!/bin/bash

package_name=$1

root_directory=$(pwd)
script_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $root_directory

source $script_directory/functions
source $root_directory/tools/install-functions

. $root_directory/package/$package_name/package

. $root_directory/tools/setenv

echo_color yellow "Installing $package_fullname-$version to staging"

run_command "cd $build_directory"

if [ -f $root_directory/package/$package_name/install-staging ]; then
  . $root_directory/package/$package_name/install-staging
else
  install_files install $staging_directory
fi
if [ $? -ne 0 ]; then
  echo_color red "Installing $package_fullname-$version to staging failed!"
  exit 1
fi

if [ -f $root_directory/package/$package_name/post-install-staging ]; then
  echo_color green "Running post-install-staging"
  . $root_directory/package/$package_name/post-install-staging
fi

run_command "touch $build_directory/.stamp_installed"
