#!/bin/bash

package_name=$1

root_directory=$(pwd)
script_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $root_directory

source $script_directory/functions

. $root_directory/package/$package_name/package

. $root_directory/tools/setenv

echo_color yellow "Installing $package_fullname-$version to target"

run_command "cd $build_directory"

. $root_directory/package/$package_name/install
if [ $? -ne 0 ]; then
  echo_color red "Installing $package_fullname-$version to target failed!"
  exit 1
fi

run_command "touch $build_directory/.stamp_target_installed"
