#!/bin/bash

package_full=$1

root_directory=$(pwd)
script_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $root_directory

source $script_directory/functions
source $script_directory/install-functions

. $root_directory/package/$package_full/package

echo_color yellow "Patching $package-$version"
run_command "cd $root_directory/build/$package-$version"

if [ ! -d $root_directory/patches/$package-$version ] ; then
	echo_color yellow "No patches to apply"
else
  patch_files=$root_directory/patches/$package-$version/*.patch

  for f in $patch_files
  do
    echo_color yellow "Apply patch $f ..."
    run_command "patch -p1 < $f"
  done
fi

if [ -n "$run_autogen" ]; then
  . $root_directory/tools/setenv
  run_command "cd $build_directory"
  run_command "PATH=$_PATH $run_autogen"
fi

echo_color yellow "Updating config.sub and config.guess for $package-$version"

for file in config.guess config.sub; do
  for i in $(find $root_directory/build/$package-$version -name $file); do
  	echo_color yellow "Updating $i"
    cp $root_directory/tools/gnuconfig/$file $i;
  done;
done

run_command "touch $root_directory/build/$package-$version/.stamp_patched"