#!/bin/bash

script_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source $script_directory/functions

$script_directory/fetch-all | tee -a build.log
if [ $? -ne 0 ]; then
  echo_color red "Failure, stopping..."
  exit 1
fi
$script_directory/clean-all | tee -a build.log
if [ $? -ne 0 ]; then
  echo_color red "Failure, stopping..."
  exit 1
fi
$script_directory/unzip-all | tee -a build.log
if [ $? -ne 0 ]; then
  echo_color red "Failure, stopping..."
  exit 1
fi
$script_directory/patch-all | tee -a build.log
if [ $? -ne 0 ]; then
  echo_color red "Failure, stopping..."
  exit 1
fi
$script_directory/build-all | tee -a build.log
if [ $? -ne 0 ]; then
  echo_color red "Failure, stopping..."
  exit 1
fi
