#!/bin/bash

script_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

$script_directory/refetch-all
if [ $? -ne 0 ]; then
  echo_color red "Failure, stopping..."
  exit 1
fi
$script_directory/clean-all
if [ $? -ne 0 ]; then
  echo_color red "Failure, stopping..."
  exit 1
fi
$script_directory/unzip-all
if [ $? -ne 0 ]; then
  echo_color red "Failure, stopping..."
  exit 1
fi
$script_directory/patch-all
if [ $? -ne 0 ]; then
  echo_color red "Failure, stopping..."
  exit 1
fi
$script_directory/build-all
if [ $? -ne 0 ]; then
  echo_color red "Failure, stopping..."
  exit 1
fi
