#!/bin/bash

script_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

$script_directory/refetch-all
$script_directory/clean-all
$script_directory/unzip-all
$script_directory/patch-all
$script_directory/build-all
