#!/bin/bash

package_name=$1

root_directory=$(pwd)
script_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $root_directory

source $script_directory/functions

. $root_directory/package/$package_name/package
. $root_directory/tools/setenv

full_filename=$(basename "$package_source")
extension="${full_filename##*.}"
filename="${full_filename%.*}"

case $extension in
xz)
  cat_tool=xzcat
  ;;
bz2)
  cat_tool=bzcat
  ;;
gz)
  cat_tool=zcat
  ;;
*)
  echo_color red "Unknown archive extension"
  echo_color green "full_filename: $full_filename"
  echo_color green "extension: $extension"
  echo_color green "filename: $filename"
  exit 1
  ;;
esac

echo_color yellow "Unpacking $package_fullname-$version"
run_command "mkdir -pv $build_directory"
run_command "$($cat_tool $root_directory/download/$package_source | tar --strip-components=1 -C $build_directory -xf -)"

if [ $? -ne 0 ]; then
  echo_color red "Unpacking $package_fullname-$version failed!"
  exit 1
fi
run_command "chmod -R +rw $build_directory"
run_command "touch $build_directory/.stamp_extracted"
