#!/bin/bash

package_fullname=wpebackend-mesa
package=wpebackend-mesa
version=c7feee8c583a8d446d3efaaefc015b14a7acaed8
package_source=$package-$version.tar.gz
package_url=https://github.com/WebPlatformForEmbedded/WPEBackend-mesa/archive/$version/$package_source
