#!/bin/bash

PATH="$_PATH" CPATH=$staging_directory/usr/include /usr/bin/make -j1 -C $build_directory DESTDIR=$staging_directory/sysroot sources
PATH="$_PATH" CPATH=$staging_directory/usr/include /usr/bin/make -j5 -C $build_directory DESTDIR=$staging_directory/sysroot
